apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-agent-demo
  template:
    metadata:
      labels:
        app: ai-agent-demo
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ai-agent-demo
          image: shreyasarjun/ai_agent_cicd:1.0
          ports:
            - containerPort: 8501
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 5
            periodSeconds: 5
  # ...existing code...